// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module nnd_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w1_i,
        w1_o,
        w1_o_ap_vld,
        w2_i,
        w2_o,
        w2_o_ap_vld,
        bias_i,
        bias_o,
        bias_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] w1_i;
output  [7:0] w1_o;
output   w1_o_ap_vld;
input  [7:0] w2_i;
output  [7:0] w2_o;
output   w2_o_ap_vld;
input  [7:0] bias_i;
output  [7:0] bias_o;
output   bias_o_ap_vld;

reg ap_idle;
reg[7:0] w1_o;
reg w1_o_ap_vld;
reg[7:0] w2_o;
reg w2_o_ap_vld;
reg[7:0] bias_o;
reg bias_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln19_fu_75_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln19_reg_343;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln19_fu_96_p3;
reg   [2:0] select_ln19_reg_347;
reg   [0:0] a_reg_352;
wire   [0:0] b_fu_112_p1;
reg   [0:0] b_reg_359;
reg   [7:0] w1_load_reg_366;
wire    ap_block_pp0_stage1_11001;
reg   [7:0] w2_load_reg_371;
reg  signed [7:0] bias_load_reg_376;
wire   [0:0] xor_ln31_fu_205_p2;
reg   [0:0] xor_ln31_reg_381;
wire   [0:0] error_fu_237_p2;
reg   [0:0] error_reg_385;
wire   [7:0] sub_ln12_fu_269_p2;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire   [7:0] sub_ln13_fu_296_p2;
wire   [7:0] sub_ln14_fu_318_p2;
reg   [2:0] i_fu_54;
wire   [2:0] i_1_fu_243_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_load;
reg   [9:0] indvar_flatten_fu_58;
wire   [9:0] add_ln19_fu_81_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln21_fu_90_p2;
wire   [7:0] select_ln28_fu_125_p3;
wire  signed [7:0] and_ln28_fu_132_p2;
wire   [7:0] select_ln28_1_fu_146_p3;
wire  signed [7:0] and_ln28_1_fu_153_p2;
wire  signed [8:0] sext_ln28_1_fu_159_p1;
wire  signed [8:0] sext_ln28_fu_138_p1;
wire   [8:0] add_ln28_fu_163_p2;
wire  signed [7:0] sext_ln28_3_fu_177_p0;
wire  signed [9:0] sext_ln28_2_fu_169_p1;
wire  signed [9:0] sext_ln28_3_fu_177_p1;
wire   [9:0] add_ln28_1_fu_181_p2;
wire   [0:0] and_ln28_2_fu_195_p2;
wire   [0:0] tmp_fu_187_p3;
wire   [7:0] add_ln10_fu_211_p2;
wire  signed [7:0] current_verdict_fu_217_p1;
wire   [0:0] c_expect_fu_199_p2;
wire   [7:0] current_verdict_fu_217_p2;
wire   [7:0] select_ln11_fu_223_p3;
wire   [7:0] and_ln11_fu_231_p2;
wire   [0:0] and_ln12_fu_253_p2;
wire   [4:0] shl_ln_fu_257_p3;
wire   [7:0] zext_ln12_fu_265_p1;
wire   [0:0] and_ln13_fu_280_p2;
wire   [4:0] shl_ln1_fu_284_p3;
wire   [7:0] zext_ln13_fu_292_p1;
wire   [4:0] shl_ln2_fu_307_p3;
wire   [7:0] zext_ln14_fu_314_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_54 = 3'd0;
#0 indvar_flatten_fu_58 = 10'd0;
#0 ap_done_reg = 1'b0;
end

nnd_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_54 <= 3'd0;
    end else if (((icmp_ln19_reg_343 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_54 <= i_1_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln19_fu_75_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_58 <= add_ln19_fu_81_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_58 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_352 <= select_ln19_fu_96_p3[32'd1];
        b_reg_359 <= b_fu_112_p1;
        icmp_ln19_reg_343 <= icmp_ln19_fu_75_p2;
        select_ln19_reg_347 <= select_ln19_fu_96_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bias_load_reg_376 <= bias_i;
        error_reg_385 <= error_fu_237_p2;
        w1_load_reg_366 <= w1_i;
        w2_load_reg_371 <= w2_i;
        xor_ln31_reg_381 <= xor_ln31_fu_205_p2;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_75_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_58;
    end
end

always @ (*) begin
    if (((xor_ln31_reg_381 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_o = sub_ln14_fu_318_p2;
    end else begin
        bias_o = bias_i;
    end
end

always @ (*) begin
    if (((xor_ln31_reg_381 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_o_ap_vld = 1'b1;
    end else begin
        bias_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln31_reg_381 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w1_o = sub_ln12_fu_269_p2;
    end else begin
        w1_o = w1_i;
    end
end

always @ (*) begin
    if (((xor_ln31_reg_381 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w1_o_ap_vld = 1'b1;
    end else begin
        w1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln31_reg_381 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_o = sub_ln13_fu_296_p2;
    end else begin
        w2_o = w2_i;
    end
end

always @ (*) begin
    if (((xor_ln31_reg_381 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_o_ap_vld = 1'b1;
    end else begin
        w2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_211_p2 = ($signed(and_ln28_1_fu_153_p2) + $signed(and_ln28_fu_132_p2));

assign add_ln19_fu_81_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln28_1_fu_181_p2 = ($signed(sext_ln28_2_fu_169_p1) + $signed(sext_ln28_3_fu_177_p1));

assign add_ln28_fu_163_p2 = ($signed(sext_ln28_1_fu_159_p1) + $signed(sext_ln28_fu_138_p1));

assign and_ln11_fu_231_p2 = (select_ln11_fu_223_p3 & current_verdict_fu_217_p2);

assign and_ln12_fu_253_p2 = (error_reg_385 & a_reg_352);

assign and_ln13_fu_280_p2 = (error_reg_385 & b_reg_359);

assign and_ln28_1_fu_153_p2 = (w2_i & select_ln28_1_fu_146_p3);

assign and_ln28_2_fu_195_p2 = (b_reg_359 & a_reg_352);

assign and_ln28_fu_132_p2 = (w1_i & select_ln28_fu_125_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_fu_112_p1 = select_ln19_fu_96_p3[0:0];

assign c_expect_fu_199_p2 = (1'd1 ^ and_ln28_2_fu_195_p2);

assign current_verdict_fu_217_p1 = bias_i;

assign current_verdict_fu_217_p2 = ($signed(add_ln10_fu_211_p2) + $signed(current_verdict_fu_217_p1));

assign error_fu_237_p2 = (($signed(and_ln11_fu_231_p2) < $signed(8'd1)) ? 1'b1 : 1'b0);

assign i_1_fu_243_p2 = (select_ln19_reg_347 + 3'd1);

assign icmp_ln19_fu_75_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd800) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_90_p2 = ((ap_sig_allocacmp_i_load == 3'd4) ? 1'b1 : 1'b0);

assign select_ln11_fu_223_p3 = ((c_expect_fu_199_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln19_fu_96_p3 = ((icmp_ln21_fu_90_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_i_load);

assign select_ln28_1_fu_146_p3 = ((b_reg_359[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln28_fu_125_p3 = ((a_reg_352[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sext_ln28_1_fu_159_p1 = and_ln28_1_fu_153_p2;

assign sext_ln28_2_fu_169_p1 = $signed(add_ln28_fu_163_p2);

assign sext_ln28_3_fu_177_p0 = bias_i;

assign sext_ln28_3_fu_177_p1 = sext_ln28_3_fu_177_p0;

assign sext_ln28_fu_138_p1 = and_ln28_fu_132_p2;

assign shl_ln1_fu_284_p3 = {{and_ln13_fu_280_p2}, {4'd0}};

assign shl_ln2_fu_307_p3 = {{error_reg_385}, {4'd0}};

assign shl_ln_fu_257_p3 = {{and_ln12_fu_253_p2}, {4'd0}};

assign sub_ln12_fu_269_p2 = (w1_load_reg_366 - zext_ln12_fu_265_p1);

assign sub_ln13_fu_296_p2 = (w2_load_reg_371 - zext_ln13_fu_292_p1);

assign sub_ln14_fu_318_p2 = ($signed(bias_load_reg_376) - $signed(zext_ln14_fu_314_p1));

assign tmp_fu_187_p3 = add_ln28_1_fu_181_p2[32'd9];

assign xor_ln31_fu_205_p2 = (tmp_fu_187_p3 ^ and_ln28_2_fu_195_p2);

assign zext_ln12_fu_265_p1 = shl_ln_fu_257_p3;

assign zext_ln13_fu_292_p1 = shl_ln1_fu_284_p3;

assign zext_ln14_fu_314_p1 = shl_ln2_fu_307_p3;

endmodule //nnd_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2
