// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nnd_nnd,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-ftg256-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.786000,HLS_SYN_LAT=803,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=81,HLS_SYN_LUT=379,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module nnd (
        ap_clk,
        ap_rst,
        a,
        b,
        c
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input  [0:0] a;
input  [0:0] b;
output  [0:0] c;

reg   [0:0] isTrained;
reg   [7:0] w1;
reg   [7:0] w2;
reg   [7:0] bias;
reg   [0:0] b_read_reg_152;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] a_read_reg_157;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_done;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_idle;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_ready;
wire   [7:0] grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w1_o;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w1_o_ap_vld;
wire   [7:0] grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w2_o;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w2_o_ap_vld;
wire   [7:0] grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_bias_o;
wire    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_bias_o_ap_vld;
reg    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start_reg;
wire   [0:0] isTrained_load_load_fu_77_p1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [7:0] select_ln59_fu_95_p3;
wire   [7:0] select_ln59_1_fu_108_p3;
wire   [7:0] and_ln59_1_fu_115_p2;
wire   [7:0] and_ln59_fu_102_p2;
wire   [7:0] add_ln59_fu_125_p2;
wire   [7:0] z_fu_131_p2;
wire   [0:0] tmp_fu_137_p3;
reg   [2:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 isTrained = 1'd0;
#0 w1 = 8'd48;
#0 w2 = 8'd80;
#0 bias = 8'd112;
#0 ap_CS_fsm = 3'd1;
#0 grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start_reg = 1'b0;
end

nnd_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2 grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start),
    .ap_done(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_done),
    .ap_idle(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_idle),
    .ap_ready(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_ready),
    .w1_i(w1),
    .w1_o(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w1_o),
    .w1_o_ap_vld(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w1_o_ap_vld),
    .w2_i(w2),
    .w2_o(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w2_o),
    .w2_o_ap_vld(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w2_o_ap_vld),
    .bias_i(bias),
    .bias_o(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_bias_o),
    .bias_o_ap_vld(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_bias_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start_reg <= 1'b0;
    end else begin
        if (((isTrained_load_load_fu_77_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start_reg <= 1'b1;
        end else if ((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_ready == 1'b1)) begin
            grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_read_reg_157 <= a;
        b_read_reg_152 <= b;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_bias_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        bias <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_bias_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        isTrained <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        w1 <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        w2 <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_w2_o;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((isTrained_load_load_fu_77_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_fu_125_p2 = (and_ln59_1_fu_115_p2 + and_ln59_fu_102_p2);

assign and_ln59_1_fu_115_p2 = (w2 & select_ln59_1_fu_108_p3);

assign and_ln59_fu_102_p2 = (w1 & select_ln59_fu_95_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign c = (tmp_fu_137_p3 ^ 1'd1);

assign grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start = grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_67_ap_start_reg;

assign isTrained_load_load_fu_77_p1 = isTrained;

assign select_ln59_1_fu_108_p3 = ((b_read_reg_152[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln59_fu_95_p3 = ((a_read_reg_157[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign tmp_fu_137_p3 = z_fu_131_p2[32'd7];

assign z_fu_131_p2 = (add_ln59_fu_125_p2 + bias);

endmodule //nnd
