-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xorg_nnd is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (0 downto 0);
    b : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of xorg_nnd is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal isTrained : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal w1 : STD_LOGIC_VECTOR (7 downto 0) := "00110000";
    signal w2 : STD_LOGIC_VECTOR (7 downto 0) := "01010000";
    signal bias : STD_LOGIC_VECTOR (7 downto 0) := "01110000";
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_idle : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_ready : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w1_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w1_o_ap_vld : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w2_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w2_o_ap_vld : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_bias_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_bias_o_ap_vld : STD_LOGIC;
    signal grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal isTrained_load_load_fu_58_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal select_ln59_fu_76_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln59_1_fu_89_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln59_1_fu_96_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln59_fu_83_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln59_fu_106_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal z_fu_112_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_118_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln60_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component xorg_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w1_i : IN STD_LOGIC_VECTOR (7 downto 0);
        w1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        w1_o_ap_vld : OUT STD_LOGIC;
        w2_i : IN STD_LOGIC_VECTOR (7 downto 0);
        w2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        w2_o_ap_vld : OUT STD_LOGIC;
        bias_i : IN STD_LOGIC_VECTOR (7 downto 0);
        bias_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        bias_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48 : component xorg_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start,
        ap_done => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done,
        ap_idle => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_idle,
        ap_ready => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_ready,
        w1_i => w1,
        w1_o => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w1_o,
        w1_o_ap_vld => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w1_o_ap_vld,
        w2_i => w2,
        w2_o => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w2_o,
        w2_o_ap_vld => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w2_o_ap_vld,
        bias_i => bias,
        bias_o => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_bias_o,
        bias_o_ap_vld => grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_bias_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_return_preg <= xor_ln60_fu_126_p2;
                end if; 
            end if;
        end if;
    end process;


    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (isTrained_load_load_fu_58_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_bias_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                bias <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_bias_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                isTrained <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w1_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                w1 <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w2_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                w2 <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_w2_o;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done, isTrained_load_load_fu_58_p1, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (isTrained_load_load_fu_58_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_start = ap_const_logic_1) and (isTrained_load_load_fu_58_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln59_fu_106_p2 <= std_logic_vector(unsigned(and_ln59_1_fu_96_p2) + unsigned(and_ln59_fu_83_p2));
    and_ln59_1_fu_96_p2 <= (w2 and select_ln59_1_fu_89_p3);
    and_ln59_fu_83_p2 <= (w1 and select_ln59_fu_76_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done)
    begin
        if ((grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state3, xor_ln60_fu_126_p2, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_return <= xor_ln60_fu_126_p2;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start <= grp_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2_fu_48_ap_start_reg;
    isTrained_load_load_fu_58_p1 <= isTrained;
    select_ln59_1_fu_89_p3 <= 
        ap_const_lv8_FF when (b(0) = '1') else 
        ap_const_lv8_0;
    select_ln59_fu_76_p3 <= 
        ap_const_lv8_FF when (a(0) = '1') else 
        ap_const_lv8_0;
    tmp_fu_118_p3 <= z_fu_112_p2(7 downto 7);
    xor_ln60_fu_126_p2 <= (tmp_fu_118_p3 xor ap_const_lv1_1);
    z_fu_112_p2 <= std_logic_vector(unsigned(add_ln59_fu_106_p2) + unsigned(bias));
end behav;
