-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xorg_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    w1_i : IN STD_LOGIC_VECTOR (7 downto 0);
    w1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    w1_o_ap_vld : OUT STD_LOGIC;
    w2_i : IN STD_LOGIC_VECTOR (7 downto 0);
    w2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    w2_o_ap_vld : OUT STD_LOGIC;
    bias_i : IN STD_LOGIC_VECTOR (7 downto 0);
    bias_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    bias_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of xorg_nnd_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_320 : STD_LOGIC_VECTOR (9 downto 0) := "1100100000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln19_fu_75_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln19_reg_343 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln19_fu_96_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln19_reg_347 : STD_LOGIC_VECTOR (2 downto 0);
    signal a_reg_352 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_fu_112_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_reg_359 : STD_LOGIC_VECTOR (0 downto 0);
    signal w1_load_reg_366 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal w2_load_reg_371 : STD_LOGIC_VECTOR (7 downto 0);
    signal bias_load_reg_376 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln31_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln31_reg_381 : STD_LOGIC_VECTOR (0 downto 0);
    signal error_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal error_reg_385 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln12_fu_269_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sub_ln13_fu_296_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln14_fu_318_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_54 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal i_1_fu_243_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_58 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln19_fu_81_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln21_fu_90_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln28_fu_125_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln28_fu_132_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln28_1_fu_146_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln28_1_fu_153_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln28_1_fu_159_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln28_fu_138_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln28_fu_163_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln28_3_fu_177_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln28_2_fu_169_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln28_3_fu_177_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln28_1_fu_181_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln28_2_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_187_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_211_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_verdict_fu_217_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal c_expect_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_verdict_fu_217_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln11_fu_223_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln11_fu_231_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln12_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_257_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln12_fu_265_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln13_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln1_fu_284_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln13_fu_292_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln2_fu_307_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln14_fu_314_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component xorg_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component xorg_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_54 <= ap_const_lv3_0;
            elsif (((icmp_ln19_reg_343 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                i_fu_54 <= i_1_fu_243_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln19_fu_75_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_58 <= add_ln19_fu_81_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_58 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_reg_352 <= select_ln19_fu_96_p3(1 downto 1);
                b_reg_359 <= b_fu_112_p1;
                icmp_ln19_reg_343 <= icmp_ln19_fu_75_p2;
                select_ln19_reg_347 <= select_ln19_fu_96_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                bias_load_reg_376 <= bias_i;
                error_reg_385 <= error_fu_237_p2;
                w1_load_reg_366 <= w1_i;
                w2_load_reg_371 <= w2_i;
                xor_ln31_reg_381 <= xor_ln31_fu_205_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln10_fu_211_p2 <= std_logic_vector(signed(and_ln28_1_fu_153_p2) + signed(and_ln28_fu_132_p2));
    add_ln19_fu_81_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv10_1));
    add_ln28_1_fu_181_p2 <= std_logic_vector(signed(sext_ln28_2_fu_169_p1) + signed(sext_ln28_3_fu_177_p1));
    add_ln28_fu_163_p2 <= std_logic_vector(signed(sext_ln28_1_fu_159_p1) + signed(sext_ln28_fu_138_p1));
    and_ln11_fu_231_p2 <= (select_ln11_fu_223_p3 and current_verdict_fu_217_p2);
    and_ln12_fu_253_p2 <= (error_reg_385 and a_reg_352);
    and_ln13_fu_280_p2 <= (error_reg_385 and b_reg_359);
    and_ln28_1_fu_153_p2 <= (w2_i and select_ln28_1_fu_146_p3);
    and_ln28_2_fu_195_p2 <= (b_reg_359 and a_reg_352);
    and_ln28_fu_132_p2 <= (w1_i and select_ln28_fu_125_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln19_fu_75_p2)
    begin
        if (((icmp_ln19_fu_75_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_54, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_54;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_58)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_58;
        end if; 
    end process;

    b_fu_112_p1 <= select_ln19_fu_96_p3(1 - 1 downto 0);

    bias_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, bias_i, xor_ln31_reg_381, ap_block_pp0_stage0, sub_ln14_fu_318_p2)
    begin
        if (((xor_ln31_reg_381 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_o <= sub_ln14_fu_318_p2;
        else 
            bias_o <= bias_i;
        end if; 
    end process;


    bias_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, xor_ln31_reg_381)
    begin
        if (((xor_ln31_reg_381 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bias_o_ap_vld <= ap_const_logic_1;
        else 
            bias_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    c_expect_fu_199_p2 <= (ap_const_lv1_1 xor and_ln28_2_fu_195_p2);
    current_verdict_fu_217_p1 <= bias_i;
    current_verdict_fu_217_p2 <= std_logic_vector(unsigned(add_ln10_fu_211_p2) + unsigned(current_verdict_fu_217_p1));
    error_fu_237_p2 <= "1" when (signed(and_ln11_fu_231_p2) < signed(ap_const_lv8_1)) else "0";
    i_1_fu_243_p2 <= std_logic_vector(unsigned(select_ln19_reg_347) + unsigned(ap_const_lv3_1));
    icmp_ln19_fu_75_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv10_320) else "0";
    icmp_ln21_fu_90_p2 <= "1" when (ap_sig_allocacmp_i_load = ap_const_lv3_4) else "0";
    select_ln11_fu_223_p3 <= 
        ap_const_lv8_FF when (c_expect_fu_199_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln19_fu_96_p3 <= 
        ap_const_lv3_0 when (icmp_ln21_fu_90_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln28_1_fu_146_p3 <= 
        ap_const_lv8_FF when (b_reg_359(0) = '1') else 
        ap_const_lv8_0;
    select_ln28_fu_125_p3 <= 
        ap_const_lv8_FF when (a_reg_352(0) = '1') else 
        ap_const_lv8_0;
        sext_ln28_1_fu_159_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln28_1_fu_153_p2),9));

        sext_ln28_2_fu_169_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln28_fu_163_p2),10));

    sext_ln28_3_fu_177_p0 <= bias_i;
        sext_ln28_3_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln28_3_fu_177_p0),10));

        sext_ln28_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(and_ln28_fu_132_p2),9));

    shl_ln1_fu_284_p3 <= (and_ln13_fu_280_p2 & ap_const_lv4_0);
    shl_ln2_fu_307_p3 <= (error_reg_385 & ap_const_lv4_0);
    shl_ln_fu_257_p3 <= (and_ln12_fu_253_p2 & ap_const_lv4_0);
    sub_ln12_fu_269_p2 <= std_logic_vector(unsigned(w1_load_reg_366) - unsigned(zext_ln12_fu_265_p1));
    sub_ln13_fu_296_p2 <= std_logic_vector(unsigned(w2_load_reg_371) - unsigned(zext_ln13_fu_292_p1));
    sub_ln14_fu_318_p2 <= std_logic_vector(signed(bias_load_reg_376) - signed(zext_ln14_fu_314_p1));
    tmp_fu_187_p3 <= add_ln28_1_fu_181_p2(9 downto 9);

    w1_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, w1_i, xor_ln31_reg_381, sub_ln12_fu_269_p2, ap_block_pp0_stage0)
    begin
        if (((xor_ln31_reg_381 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w1_o <= sub_ln12_fu_269_p2;
        else 
            w1_o <= w1_i;
        end if; 
    end process;


    w1_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, xor_ln31_reg_381)
    begin
        if (((xor_ln31_reg_381 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w1_o_ap_vld <= ap_const_logic_1;
        else 
            w1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    w2_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, w2_i, xor_ln31_reg_381, ap_block_pp0_stage0, sub_ln13_fu_296_p2)
    begin
        if (((xor_ln31_reg_381 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w2_o <= sub_ln13_fu_296_p2;
        else 
            w2_o <= w2_i;
        end if; 
    end process;


    w2_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, xor_ln31_reg_381)
    begin
        if (((xor_ln31_reg_381 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w2_o_ap_vld <= ap_const_logic_1;
        else 
            w2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln31_fu_205_p2 <= (tmp_fu_187_p3 xor and_ln28_2_fu_195_p2);
    zext_ln12_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_257_p3),8));
    zext_ln13_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_284_p3),8));
    zext_ln14_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_307_p3),8));
end behav;
