-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity orr is
port (
    a : IN STD_LOGIC_VECTOR (0 downto 0);
    b : IN STD_LOGIC_VECTOR (0 downto 0);
    c : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of orr is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "orr_orr,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-ftg256-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.508000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=26,HLS_VERSION=2025_2}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal b_cast_fu_63_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal a_cast_fu_59_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp2_fu_67_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp1_fu_73_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal z_fu_81_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_87_p3 : STD_LOGIC_VECTOR (0 downto 0);


begin



    a_cast_fu_59_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a),2));
    b_cast_fu_63_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b),2));
    c <= (tmp_fu_87_p3 xor ap_const_lv1_1);
    tmp1_fu_73_p3 <= (tmp2_fu_67_p2 & ap_const_lv4_0);
    tmp2_fu_67_p2 <= std_logic_vector(unsigned(b_cast_fu_63_p1) + unsigned(a_cast_fu_59_p1));
    tmp_fu_87_p3 <= z_fu_81_p2(5 downto 5);
    z_fu_81_p2 <= std_logic_vector(unsigned(tmp1_fu_73_p3) + unsigned(ap_const_lv6_38));
end behav;
